# Generated by Django 5.2.5 on 2026-01-03 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramLevel', models.CharField(max_length=255)),
                ('SpecializationName', models.CharField(max_length=255, null=True)),
                ('AcademicLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.academiclevel')),
            ],
        ),
    ]
