# Generated by Django 5.2.5 on 2026-01-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_academiclevel_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='SpecializationName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
