# Generated by Django 5.2.5 on 2026-01-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_program_specializationname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='AcademicLevel',
            new_name='academic_level',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='ProgramLevel',
            new_name='program_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='SpecializationName',
        ),
        migrations.AddField(
            model_name='program',
            name='specialization',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
