# Generated by Django 5.2.5 on 2026-01-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='program_id',
            new_name='program',
        ),
    ]
