# Generated by Django 5.2.5 on 2026-01-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_lecturer_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='room_capacity',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
