# Generated by Django 5.2.5 on 2026-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_lecturer_room_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
