# Generated by Django 5.2.5 on 2026-01-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_course_credit_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_day', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_time', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.IntegerField(default=1)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
    ]
