# Generated by Django 5.2.5 on 2026-01-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_timetableslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.academiclevel'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
