# Generated by Django 5.2.5 on 2026-01-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_course_credit_hours_alter_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='assigned_venue',
        ),
        migrations.AddField(
            model_name='course',
            name='expected_students',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(related_name='lecturers', to='myapp.course'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='assigned_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.room'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='assigned_day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='assigned_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
