# Generated by Django 5.2.5 on 2026-01-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_lecturer_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='main_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.mainprogram'),
            preserve_default=False,
        ),
    ]
