# Generated by Django 5.2.5 on 2026-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_mainprogram_program_main_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_name',
        ),
        migrations.AlterField(
            model_name='program',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
