# Generated by Django 5.2.5 on 2026-01-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_course_program_course_programs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='programs',
            new_name='program',
        ),
    ]
