# Generated by Django 5.2.5 on 2026-01-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_programs_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
            preserve_default=False,
        ),
    ]
